Repository spryker-sdk/integrator, pull requests merged in 2022-03, with the labels that each got.

#18 Add docs
  docs/README.md
  docs/manifest-types.md
Labels: documentation

#20 TE-10889 added literal value processing
  docs/manifest-types.md
  src/Builder/ClassModifier/CommonClassModifier.php
  src/Builder/Exception/LiteralValueParsingException.php
  src/ManifestStrategy/ConfigureEnvManifestStrategy.php
  tests/SprykerSdkTest/Integrator/BaseTestCase.php
  tests/SprykerSdkTest/Integrator/Builder/ClassLoader/ClassLoaderTest.php
  tests/SprykerSdkTest/Integrator/Builder/ClassModifier/ClassModifierTest.php
  tests/_tests_files/test_integrator_config_module_class_modifier.php
Labels: improvement

#22 Cleanup phpstan
  .github/workflows/ci.yml
  composer.json
  phpcs.xml
  phpcs.xml.dist
  phpstan.neon
  src/Builder/Checker/ClassMethodChecker.php
  src/Builder/ClassGenerator/ClassGeneratorInterface.php
  src/Builder/ClassLoader/ClassLoader.php
  src/Builder/ClassModifier/ClassInstanceClassModifier.php
  src/Builder/ClassModifier/ClassListModifier.php
  src/Builder/ClassModifier/CommonClassModifier.php
  src/Builder/ClassModifier/GlueRelationshipModifier.php
  src/Builder/ClassResolver/ClassResolver.php
  src/Builder/ClassWriter/ClassFileWriter.php
  src/Builder/Finder/ClassNodeFinderInterface.php
  src/Builder/Printer/ClassPrinter.php
  src/Common/UtilText/Filter/CamelCaseToSeparator.php
  src/Common/UtilText/Filter/SeparatorToCamelCase.php
  src/Dependency/Console/ComposerInputOutputAdapter.php
  src/Dependency/Console/InputOutputInterface.php
  src/Executor/ManifestExecutor.php
  src/IntegratorConfig.php
  src/Manifest/ManifestReader.php
  src/ManifestStrategy/ConfigureModuleManifestStrategy.php
  src/ManifestStrategy/UnwireGlueRelationshipManifestStrategy.php
  src/ManifestStrategy/UnwirePluginManifestStrategy.php
  src/ManifestStrategy/UnwireWidgetManifestStrategy.php
  src/ManifestStrategy/WireGlueRelationshipManifestStrategy.php
  src/ManifestStrategy/WirePluginManifestStrategy.php
  src/ManifestStrategy/WireWidgetManifestStrategy.php
  src/ModuleFinder/Module/ModuleFinder/ModuleFinder.php
  src/ModuleFinder/Module/ModuleMatcher/ModuleMatcher.php
  src/ModuleFinder/Module/ProjectModuleFinder/ProjectModuleFinder.php
  src/ModuleFinder/Package/PackageFinder/PackageFinder.php
  src/Transfer/AbstractTransfer.php
  src/Transfer/ApplicationTransfer.php
  src/Transfer/ClassInformationTransfer.php
  src/Transfer/MethodInformationTransfer.php
  src/Transfer/ModuleFilterTransfer.php
  src/Transfer/ModuleTransfer.php
  src/Transfer/OrganizationTransfer.php
  src/Transfer/PackageTransfer.php
  tests/SprykerSdkTest/Integrator/BaseTestCase.php
  tests/SprykerSdkTest/Integrator/Builder/ClassModifier/ClassModifierTest.php
  tests/SprykerSdkTest/Integrator/Composer/ComposerLockReaderTest.php
  tests/SprykerSdkTest/Integrator/Helper/ClassHelperTest.php
  tests/_data/project_mock/src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php
  tests/_data/project_mock/src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php
  tests/_data/project_mock/src/Pyz/Zed/TestIntegratorDefault/TestIntegratorDefaultConfig.php
  tests/_data/project_mock/src/Pyz/Zed/TestIntegratorWirePlugin/TestIntegratorWirePluginDependencyProvider.php
  tests/_tests_files/test_integrator_config_module_class_modifier.php
  tests/_tests_files/test_integrator_configure_module.php
  tests/_tests_files/test_integrator_default_dependency_provider.php
  tests/_tests_files/test_integrator_unwire_glue_relationship.php
  tests/_tests_files/test_integrator_unwire_widget.php
  tests/_tests_files/test_integrator_wire_glue_relationship.php
  tests/_tests_files/test_integrator_wire_plugin_dependency_provider.php
  tests/_tests_files/test_integrator_wire_widget.php
Labels: bug, prio
